unbind r 
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows 1


bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -n M-k resize-pane -U 5
bind -n M-j resize-pane -D 5
bind -n M-h resize-pane -L 5
bind -n M-l resize-pane -R 5


bind-key X kill-session
bind-key x kill-pane
bind-key s choose-session
bind-key S command-prompt -p "Session name:" "new-session -A -s '%%'"
bind . command-prompt -I "#S" "rename-session '%%'"
bind q run-shell "tmux list-sessions -F '#S' | fzf --reverse | xargs -r tmux kill-session -t"

set-option -g status-position top

# List of plugins
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '2kabhishek/tmux2k'

# use a theme
set -g @tmux2k-theme 'duo icons'
# to show icons only
set -g @tmux2k-icons-only true
# to customize duo bg and fg
# to set powerline symbols
set -g @tmux2k-right-sep  # alternate right status bar sep
set -g @tmux2k-window-list-right-sep  # alternate window list right sep
# to not show powerline
set -g @tmux2k-cpu-display-load false
# set session icon, accpets: `session`, 'window`, or any string
# set -g @tmux2k-session-icon "" # `#W` for window name
# set -g @tmux2k-network-wifi-icon ""
# set -g @tmux2k-ethernet-wifi-icon ""
# set -g @tmux2k-network-offline-icon ""
# set -g @tmux2k-ram-icon ""
#

set -g @tmux2k-left-plugins "session git"
set -g @tmux2k-right-plugins "battery time"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
